**The curse of dimensionality**

> As the number of dimensionality increases, the number of observation needed to establish significant relationship between variables grow significantly. 

> if we simulate a random stock for 20 days, 0 represents down and 1 represents up, then we flip a coin enough to mimic stock's behavior. If we flip a coin enough time, we will find the "perfect coin" to predict stock price.

In [1]:
import numpy as np
import pandas as pd


stock = np.random.randint(low = 0, high = 2, size = 10)
stock

array([0, 1, 1, 0, 1, 0, 1, 0, 0, 0])

In [2]:
coins = []
coin = np.random.randint(low = 0, high = 2, size = 10)
data = pd.DataFrame()


while (coin != stock).any():
    
    data['Coin ' + str(len(list(data)))] = coin 
    
    coin = np.random.randint(low = 0, high = 2, size = 10)
    

data['Coin ' + str(len(list(data)))] = coin
data['stock'] = stock

In [4]:
data.iloc[:,-11:]

,Coin 3107,Coin 3108,Coin 3109,Coin 3110,Coin 3111,Coin 3112,Coin 3113,Coin 3114,Coin 3115,Coin 3116,stock
0,0,1,0,1,0,0,0,0,1,0,0
1,0,1,0,1,0,1,1,0,0,1,1
2,1,0,1,1,1,1,0,1,1,1,1
3,0,1,0,1,1,1,1,1,1,0,0
4,0,1,0,0,1,1,0,1,0,1,1
5,0,1,0,0,1,0,0,1,0,0,0
6,1,1,1,0,1,1,1,1,1,1,1
7,1,0,0,1,0,0,0,0,0,0,0
8,1,1,0,1,0,0,1,0,0,0,0
9,1,0,0,1,1,1,0,0,1,0,0

> At this time, we have found the "perfect coin" to mimic stock behavior, Should we use this stock to facilitate our investment strategy.